### ISSUE TITLE
No model update from PUT request result in beta.15

### ISSUE THREAD

**Issue by plcarmel** [emberjs/data#2900]
ember-data 1.0.0-beta.15 is not updating the model from the result of a PUT request anymore.

I downgraded ember-data to 1.0.0-beta.14 and the bug is not present in this version.

**Comment by seanpdoyle** [comment]
Could you distill an example demonstrating this behavior into a JSbin?

**Comment by plcarmel** [comment]
I am very short on time but I will try.

**Comment by bmac** [comment]
Hi @plcarmel, Did you have any luck tracking down this issue? I attempted to put together a jsbin based on what you described but I was unable to reproduce the issue. http://emberjs.jsbin.com/xutihotapi/1/edit?html,js

**Comment by plcarmel** [comment]
Hi @bmac.  Sorry for the delay.  No, I did not have any luck yet.  I checked your jsbin and I saw it is working fine.  So I upgraded my code again to beta.15 just to make sure I could still reproce the problem and I still can.  I will have some slack next week and I am going to investigate the problem.

**Comment by plcarmel** [comment]
Problem is still present in beta.16.1

**Comment by plcarmel** [comment]
Ok, I toyed with the jsbin and I finally got something.

http://emberjs.jsbin.com/texixi/1/edit

Press the "save" button.  It is going to work fine.  Now change the value in the textbox.  Press the "save" button again. It is not going to work; the value will stay the same.

Switch to the beta.14 ember-data file (see commented out line) and do the sequence.  Now, it is going to work every time.

**Comment by bmac** [comment]
I just tried out the above jsbin using the latest master build and this issue appears to have been fixed. http://emberjs.jsbin.com/wiveqejive/1/edit?html,css,js

**Comment by plcarmel** [comment]
I just tried it with the link you provided and it seems the problem is still present. Please follow my instructions carefully.  It works for the first save but not for the subsequent ones.

**Comment by bmac** [comment]
You are correct. Sorry about that. I'm currently working updating @wecc's pr #2998. Should have a fix for this soon.

**Comment by plcarmel** [comment]
No worries, thanks.
