### ISSUE TITLE
Tests failing after upgrading to 1.0.0-beta16

### ISSUE THREAD

**Issue by pmdarrow** [emberjs/data#2924]
After upgrading to 1.0.0-beta16, all of my models tests are failing on this line: https://github.com/emberjs/data/commit/31583dbac284db55102f5a6dfb08af5e18a2971b#diff-1636bea36bbe333a834ea11fbfbde48dR1876. It appears `this._containerCache` is undefined and therefore `this._containerCache[key]` throws an exception. Each model test seems to pass fine when run in isolation, but when I test an entire module or run the whole suite, I get exception errors for each test.

**Comment by bmac** [comment]
hmm. I wonder if this line is causing the issue https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1929. It should only get run when the store is being destroyed. Could your tests be holding on to and old store?

**Comment by pmdarrow** [comment]
After playing around in the debugger, it seems like you might be right—despite `this._containerCache = Ember.create(null);` running during the execution of `qunit.module.setup()` and `delete this._containerCache;` running during `qunit.module.teardown()`, `this._containerCache` is still `undefined` in `retrieveManagedInstance`. 

Is the problem with https://github.com/stefanpenner/ember-test-helpers/blob/master/lib/ember-test-helpers/module-for.js#L103?

**Comment by bmac** [comment]
It could be related [ember-test-helpers](https://github.com/stefanpenner/ember-test-helpers/blob/master/lib/ember-test-helpers/module-for.js#L114-L118). I know the `subject()` helper was know to reuse an old container in the past. I'm not sure if its still an issue. https://github.com/rwjblue/ember-qunit/issues/81

**Comment by jrjohnson** [comment]
I'm seeing a different error 
```
 Cannot read property 'adapter:user' of undefined
```
But it seems to also be related to the subject() test helper.  I worked around it by creating the model using createRecord when I needed it instead of calling this.subject()

**Comment by igorT** [comment]
ping @rwjblue

**Comment by pmdarrow** [comment]
That's the same issue I'm experiencing @jrjohnson, I just tracked down the exact line throwing the exception.

**Comment by bmac** [comment]
@pmdarrow Do you mind sharing what line was throwing the exception?

**Comment by rwjblue** [comment]
Should be fixed once https://github.com/switchfly/ember-test-helpers/pull/28 is merged and released in a new ember-qunit version.

**Comment by pmdarrow** [comment]
@bmac the line I linked in my first post is where the exception is being thrown. Looks like it's been fixed elsewhere so you can probably close this.

**Comment by rwjblue** [comment]
ember-qunit@0.3.0 is release fixing this...

**Comment by novaugust** [comment]
I'm seeing this same error trying to upgrade ghost to 1.11 (tryghost/ghost#5094), but we're on mocha rather than qunit. Can anyone point me towards a solution for that?

**Comment by bmac** [comment]
Sounds like the same issue. @dgeb which version of ember-mocha uses `v0.4.1` of ember-test-helpers?

**Comment by rwjblue** [comment]
@novaugust - Update to 0.6.0 of ember-mocha in your `bower.json` (no changes needed in ember-cli-mocha other than the blueprint so you can just get started with ember-mocha@0.6.0).

**Comment by novaugust** [comment]
Thanks gents, fixed now

**Comment by cibernox** [comment]
I'm still facing this bug using the latest and greatest versions of everything:

`ember-data: beta.18`
`ember: 1.12`
`ember-qunit: 0.4.0`
`ember-cli-qunit: 0.3.14`

On the `Ember.run(application, 'destroy');` of the teardown of some acceptance tests the `_containerCache` is undefined.

**Comment by cibernox** [comment]
I've found the change in my code that triggered this:

I changed the cleaning of the state of a `/new` route from the `willTransition` action to the `deactivate` hook:

This works:
```js
  actions: {
    willTransition() {
      const spellingTest = this.modelFor(this.routeName);
      spellingTest.get('trays').filterBy('isNew').forEach(function (tray) {
        if (tray.get('isNew')) {
          tray.get('tasks').filterBy('isNew').forEach(t => t.destroyRecord());
          tray.destroyRecord();
        }
      });
      return true;
    },
    // ...
  }
```

This fails:

```js
  deactivate() {
    const spellingTest = this.modelFor(this.routeName);
    spellingTest.get('trays').filterBy('isNew').forEach(function (tray) {
      if (tray.get('isNew')) {
        tray.get('tasks').filterBy('isNew').forEach(t => t.destroyRecord());
        tray.destroyRecord();
      }
    });
    return true;
  }
```

**Comment by olivierlesnicki** [comment]
Seeing same issues with ember-qunit 0.3.9
