### ISSUE TITLE
DEPRECATION: `lookupFactory` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container.

### ISSUE THREAD

**Issue by sunil-shrestha** [emberjs/data#3051]
Originally posted at https://github.com/emberjs/ember.js/issues/11009

Just updated my Ember.js app to latest and tried to get Ember FastBoot running. Somehow it managed to run server with "ember s" giving some warning on browser.

However, running "ember fastboot" produces following warnings on console and does not seem to go anywhere from here.

    Built project successfully. Stored in "dist".     
    DEBUG: -------------------------------
    DEBUG: Ember      : 1.13.0-beta.1+canary.1ab4ccb4
    DEBUG: Ember Data : 1.0.0-beta.17+canary.8c81d416c2
    DEBUG: -------------------------------
    Ember FastBoot running at http://0.0.0.0:3000
    DEPRECATION: `lookupFactory` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.
    {anonymous}(ember)$data$lib$initializers$store$$initializeStore (<anonymous>:73828:48
    {anonymous}(Object.ember)$data$lib$setup$container$$setupContainer [as initialize]    (<anonymous>:74138:7)
    {anonymous}(<anonymous>:17751:23)
    {anonymous}(<anonymous>:17774:9)
    visit (<anonymous>:15781:7)
    visit (<anonymous>:15779:9)
    DAG.topsort (<anonymous>:15893:11)
    Namespace.default.extend._runInitializer (<anonymous>:17773:13)
    
    DEPRECATION: `lookup` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.
    {anonymous}(ember)$data$lib$initializers$store$$initializeStore (<anonymous>:73846:28)
    {anonymous}(Object.ember)$data$lib$setup$container$$setupContainer [as initialize]    (<anonymous>:74138:7)
    {anonymous}(<anonymous>:17751:23)
    {anonymous}(<anonymous>:17774:9)
    visit (<anonymous>:15781:7)
    visit (<anonymous>:15779:9)
    DAG.topsort (<anonymous>:15893:11)
    Namespace.default.extend._runInitializer (<anonymous>:17773:13)

Hopping that someone could guide to the right solution.

**Comment by sandstrom** [comment]
This issue should already be solved on Ember Data master (emberjs/data#2806).

A few points that may be helpful:
- deprecations aren't dangerous, they are merely informational
- you may want to try with canary data (as this is likely already solved), see: http://www.ember-cli.com/#using-canary-build-instead-of-release

**Comment by sly7-7** [comment]
@sandstrom I think this line https://github.com/emberjs/data/blob/master/packages/ember-data/lib/initializers/store.js#L21 is throwing the deprecation, unless I'm missing something this still appears on canary. I'm not sure but I think the store initializer should be split into initializer/instanceInitializer.

cc/ @fivetanley @bmac

**Comment by wecc** [comment]
1.0.0-beta.17+canary.8c81d416c2 seem to be newer than https://github.com/emberjs/data/pull/2884

**Comment by igorT** [comment]
ping @twokul

**Comment by bmac** [comment]
I've opened a [pr to try and fix this issue](https://github.com/emberjs/data/pull/3070) however, its currently blocked on this issue in Ember https://github.com/emberjs/ember.js/issues/11172.

**Comment by bmac** [comment]
Should fixed on canary after https://github.com/emberjs/data/pull/3136
