### ISSUE TITLE
[Deprecation] usage of reduce computed in errors.js

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#3327]
https://github.com/emberjs/data/blob/97f39acbe5b67157a3077e4ed124290625f00576/packages/ember-data/lib/system/model/errors.js#L112-L132

source: https://github.com/emberjs/ember.js/issues/11435

**Comment by igorT** [comment]
I believe this has been fixed

**Comment by pangratz** [comment]
@igorT yep

**Comment by yonida** [comment]
Still getting it with ember 1.13.0 and ember data 1.0.0-beta.19
How can I fix it?

**Comment by pangratz** [comment]
@yonida This should be fixed in `ember-data` `v1.13.0`
