### ISSUE TITLE
JSON-API correct handling of included entities

### ISSUE THREAD

**Issue by wwwdata** [emberjs/data#3380]
The implementation currently always loads `related` entities from the provided url. If there are ids inside a `data` object in a relation that match the ids of objects inside the `included` object, those already loaded objects must be taken instead of requesting them from the `related` url, because that is not necessary. 

basic example

```json
{
    "data": [
        {
            "type": "posts",
            "id": "1",
            "attributes": {
                "title": "JSON API paints my bikeshed!"
            },
            "relationships": {
                "author": {
                    "links": {
                        "self": "http://example.com/posts/1/relationships/author",
                        "related": "http://example.com/posts/1/author"
                    },
                    "data": {
                        "type": "people",
                        "id": "9"
                    }
                }
            },
            "links": {
                "self": "http://example.com/posts/1"
            }
        }
    ],
    "included": [
        {
            "type": "people",
            "id": "9",
            "attributes": {
                "first-name": "Dan",
                "last-name": "Gebhardt",
                "twitter": "dgeb"
            },
            "links": {
                "self": "http://example.com/people/9"
            }
        }
    ]
}
```

here, the author got already provided in the `included` object and does not need to be fetched.

**Comment by bmac** [comment]
Looks like we had a regression where the `included` links were not being loaded properly. I believe this is fixed by https://github.com/emberjs/data/pull/3379. 

@wwwdata do you mind trying http://builds.emberjs.com/canary/ember-data.js to see if the issue is fixed?

**Comment by wwwdata** [comment]
the error is still there. I wrote a small test: https://github.com/wwwdata/data/commit/36a62a21788a9fd77e8ee3f6f358a138c3282604

the `equal(passedUrl.length, 1);` fails because a second request was made. It seems that if the jsonapi adapter finds a related link, it always follows it.

**Comment by steffenbrem** [comment]
@bmac @wwwdata Is this caused by the following line? https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/relationships/state/has-many.js#L176

**Comment by steffenbrem** [comment]
Also this PR might be related: #3122

**Comment by wwwdata** [comment]
@steffenbrem yes, that is the line, when i always use the `this.findRecords()` my test works but the other tests break that rely on loading stuff from the related urls.

**Comment by wecc** [comment]
I've looked into this (including #3122) and even though it might seems trivial at first (let local data take precedence over links) I fear it's not.

We have the scenario when you have a link but no data and then fetch the data. So far so good. But if the link gets updated we want to invalidate the cache and refetch the next time we get the records. There's a test for this [here](https://github.com/emberjs/data/blob/master/packages/ember-data/tests/integration/relationships/has-many-test.js#L566-L607). Having local data take precedence over links breaks this.

Another scenario is when you have a link and then create a new local record. This means we _do_ have data but we still haven't fetched the link. In this scenario we want to fetch the link and merge the results with the newly created record and return them together. There's currently a test for this [here](https://github.com/emberjs/data/blob/master/packages/ember-data/tests/integration/relationships/has-many-test.js#L249-L287). Having local data take precedence over links breaks this too.

With JSON-API I'm suspecting it will be more and more common having both links and data returned from backends and in many of those cases the data should take precedence over links. This is absolutely something we should solve, I just don't know how yet.

**Comment by steffenbrem** [comment]
@wecc My two cents on how to solve the issues you described above. For the first scenario, couldn't you just keep the dirty state of the link, so only take data presendence if the link is not "dirty". 

For the second scenario, I think you could easily track this by checking if the specific relation you are requesting has embedded data loaded, so some property should be set on every relationship that says if is has the data or not.

I don't know if this is realistic, since I am not an Ember Data expert. But I think it shouldn't be that hard to solve it.

**Comment by wwwdata** [comment]
@steffenbrem :+1: go for it please and make a PR. I think we should just check if there are some reference IDs in the `data` object on the same level as the link and if all of these IDs can be found in the `included` object, there is no more need to fetch data from the related link. I would expect from the server to return all the references in that case.

The link however always makes sense, because you might want to check at a later time if there are more referenced entities. For example if you loaded a blog post and just want to reload comments. Maybe ember-data at sometime needs another method to explicitly force loading of related entities via a related link for this special case. But as first step it would be awesome to just take stuff from the `included` object if possible :smile:

**Comment by wecc** [comment]
@steffenbrem @wwwdata The problem is, as I see it, that we want different outcomes from two different scenarios that we're currently unable to tell apart:

1. link exist (`relationship.link`) + locally created record exist (`relationship.hasData === true`), **we want to fetch the link**
2. link exist (`relationship.link`) + we have data from server (`relationship.hasData === true`), **we do not want to fetch the link**

**Comment by steffenbrem** [comment]
@wecc So basically, we need to be able to know if the relationships has its data from the server or it is only local data. Something like that? I think that covers the issue we are having.

**Comment by krzkrzkrz** [comment]
Just to summarise and to help newcomers jumping into Ember Data and using the JSONAPIAdapter.

Theres a bug where `links.related` currently takes precedence over `data`.

Apply this workaround without having to remove the `links.related` urls from the API. When the bug is fixed, you just have to remove the `extractRelationship` function. The workaround removes any `relationship.type.related` links.

Credit to @wecc. In the application serializer (`app/pods/application/controller.js`): 

```
import DS from 'ember-data';

// https://github.com/emberjs/data/issues/3380
// Theres a bug where links.related currently takes precedence over data
// Apply this workaround without having to remove the links.related urls from the API
export default DS.JSONAPISerializer.extend({
  extractRelationship: function(relationshipHash) {
    if (relationshipHash.data && relationshipHash.links && relationshipHash.links.related) {
      delete relationshipHash.links.related;
    }
    return this._super(relationshipHash);
  }
});
```

**Comment by steffenbrem** [comment]
@krzkrzkrz smart workaround. Thanks ;)

**Comment by jcope2013** [comment]
is there an equivalent method i can override on active model serializer to do something similar? should i file an issue on https://github.com/ember-data/active-model-adapter also?

**Comment by wecc** [comment]
@jcope2013 I think you should be able to do pretty much the same if you call `this._super()` first (that will give you a JSON-API relationship back that you can work with)

**Comment by jcope2013** [comment]
@wecc that doesn't seem to work, relationshipHash comes in as a string of the modelName and what it returns when calling ``` this._super() ``` is just an object that looks like this ``` { id: 1, type: 'user' } ```

```
import DS from 'ember-data';

export default DS.ActiveModelSerializer.extend({
  isNewSerializerAPI: true,

  extractRelationship: function(relationshipHash) {
  	var data = this._super.apply(this, arguments);
        console.log(data);
        return data;
  }
});
```

**Comment by wecc** [comment]
> relationshipHash comes in to the method as a string of the modelName

yeah, that sound's really odd. can you create a separate issue with a JSBin demonstrating the issue? (preferably using your real payload)

**Comment by wwwdata** [comment]
I tried the workaround from @krzkrzkrz too. For me it sems to work if a related entity is not included in the `included` object. Then, another request is made to fetch it, if it's not already present in the store. However if I include the referenced entity, it is not loaded and empty.

Is there a better workaround at the moment that also works with `included`?

**Comment by cdunn** [comment]
Would it make sense to also distinguish between data: [] and null, the former representing from the server that there are no related records vs the latter implying that the server doesn't know and should query?

**Comment by wwwdata** [comment]
any news on the team decision? 

In order to really use ember-data with jsonapi 1.0 we need a good way to treat relationships and also make them optional if needed, so that they are requested only if needed from the specified relationship URL.

**Comment by greyhwndz** [comment]
Any update on the position of the team regarding this?

**Comment by smcclstocks** [comment]
bump

**Comment by xomaczar** [comment]
Seeing the same issue with ED@2.2.1, not event using relationship links at all (One-to-One).

```json
{
  data: {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "Rails is Omakase"
    },
    "relationships": {
      "comment": {
        "data": { "type": "comment", "id": "1" }
      }
    },
  },
 "included": [
      {
            "type": "comments",
            "id": "1",
            "attributes": {
                "author": "Dan",
                "title": "Gebhardt",
            }
        }
    ]
}
```
articleWithID1.get('comment') => makes a seperate request instead of using its "included".

**Comment by wecc** [comment]
@xomaczar I'm unable to reproduce this, see http://emberjs.jsbin.com/catohelode/edit?html,js,output

Would you be able to create a JSBin demonstrating the issue? Feel free to open a new issue since this one is old and very long.

**Comment by xomaczar** [comment]
@wecc here is the failing JSBin: http://emberjs.jsbin.com/cezowa/edit?html,js,console,output
Try removing afterModel() hook.
I'll definitely open a new issue if it's an issue after all or my misunderstanding of stuff...

**Comment by xomaczar** [comment]
@wecc is this issue legit?

**Comment by wecc** [comment]
@xomaczar not a bug, more unfortunate circumstances :)

article:1 is already loaded when you enter the second route so the promise is resolved straight away using the article in store (without comments). Your template then tries to access comments and triggers a fetch. Meanwhile ED has background reloaded your article (see the new shouldBackgroundReloadRecord hook iirc) and the comments are side loaded and displayed correctly even though you get at "failed" comments fetch.

So, the behavior you're seeing is by design, but not very easy to spot.

Ping me in Slack of you want, should be an easy fix.

**Comment by scottkidder** [comment]
> article:1 is already loaded when you enter the second route so the promise is resolved straight away using the article in store (without comments). Your template then tries to access comments and triggers a fetch. Meanwhile ED has background reloaded your article (see the new shouldBackgroundReloadRecord hook iirc) and the comments are side loaded and displayed correctly even though you get at "failed" comments fetch.

This is precisely what I am currently seeing. Right now I override shouldReloadRecord on the first model adapter to always return true, stopping the promise from being resolved straight away.

What is a better real solution here?
