### ISSUE TITLE
Can't return null to queryRecord anymore

### ISSUE THREAD

**Issue by danconnell** [emberjs/data#4310]
Previously on Ember Data 2.3.3, you could have you API return null to a call made by `queryRecord`. Now, on Ember Data 2.4.3, you get this error if you try to do that: 

`Assertion Failed: You made a `queryRecord` request for undefinedrecords, with query `[object Object]`, but the adapter's response did not have any data Error: Assertion Failed: You made a `queryRecord` request for undefinedrecords, with query `[object Object]`, but the adapter's response did not have any data`

Was this an intended change? I understand that this might not be a bug, but I also don't see this change mentioned in the changelog.

Just thought I should point it out, since it did break something for me.

**Comment by pangratz** [comment]
Thanks for reporting this @danconnell. What adapter are you using? Can you provide an ember-twiddle, demonstrating the issue? You can use [this twiddle](https://ember-twiddle.com/300ff114b6fb3a4aa37e99a1c31bbf37?fileTreeShown=false&numColumns=2&openFiles=adapters.application.js%2Capplication.route.js) as a start, it uses the `json-api` adapter. Thanks!

**Comment by pangratz** [comment]
Ah now I can reproduce the issue you're having. I had it wrong, and in the twiddle `{ data: null }` is returned which is not the same thing you return I assume.

---

The issue you're having has been fixed in #4256, which is available in `2.5.0-beta.3`. Can you try out that version and confirm that your app is working again?

**Comment by danconnell** [comment]
I'm using the rest adapter.

Tested on 2.5.0-beta.3 and it's still broken. Here's a [twiddle](https://ember-twiddle.com/0f48192ecf352f784bca0c7c80626bd8?fileTreeShown=false&numColumns=2&openFiles=adapters.application.js%2Capplication.route.js) using 2.5.0-beta.3.

**Comment by pangratz** [comment]
Looks like this is a regression. There is no assert throwing in [v2.3.3](https://ember-twiddle.com/a32b27014e1241a6f39f406a1381f9cf?fileTreeShown=false&numColumns=2&openFiles=application.route.js%2Capplication.template.hbs) but in [v2.4.3](https://ember-twiddle.com/c2ab0406c5cb7e885e2a2ae36481365c?fileTreeShown=false&numColumns=2&openFiles=application.route.js%2Capplication.template.hbs) there is.

The assertion has been added in #3916, because at that time a not very descriptive error `You must include an 'id' for undefined in an object passed to 'push'` would be thrown if the payload was empty. Maybe this is already better handled in the meantime...

**Comment by pangratz** [comment]
This has been discussed in the team meeting and the assertion for `queryRecord` should be removed and the old behavior should be restored. This will be tackled in the course of #4300.

**Comment by danconnell** [comment]
Sounds good. Thanks for the update :)

**Comment by BissyQA** [comment]
same error Assertion Failed: You made a `queryRecord` request for undefinedrecords, with query `[object Object]. Does the issue fixed in 4300? .  Is this alternate way to fix the error ?

because at that time a not very descriptive error You must include an 'id' for undefined in an object passed to 'push' would be thrown if the payload was empty.

**Comment by pangratz** [comment]
@BissyQA yes, this is addressed in #4300. Until the PR is merged and a new release is cut, you can workaround this by ensuring that you don't return an empty object as payload from the adapter, as shown [in this ember-twiddle](https://ember-twiddle.com/cd7ed68a773e567673827b3134c29615?fileTreeShown=false&numColumns=3&openFiles=routes.application.js%2Cadapters.application.js%2Ctemplates.application.hbs):

```js
import DS from "ember-data";

export default DS.RESTAdapter.extend({
  queryRecord() {
    return this._super(...arguments).then(function(payload) {
      // workaround so returned payload is not empty, remove
      // once https://github.com/emberjs/data/pull/4300
      // is merged and released
      payload._unusedKeySoPayloadIsNotEmpty = {};

      return payload;
    });
  }
});
```

**Comment by pangratz** [comment]
I am going to close this issue since #4300 has been merged and the regression has been fixed in that PR.
