### ISSUE TITLE
Assert when ManyArray.objectAt after one of the records has been unloaded

### ISSUE THREAD

**Issue by hjdivad** [emberjs/data#4758]
Although it would be nice for this to work, we do not support sparse arrays.  It would probably be better to error rather than to have undefined behaviour (as we have today).

However, it is likely better as a first step to just warn, and then to see how pervasive the warning becomes, especially in test teardown.

**Comment by mixonic** [comment]
Fixed in https://github.com/emberjs/data/pull/4896

**Comment by runspired** [comment]
Additional fix in https://github.com/emberjs/data/pull/4912

**Comment by stefanpenner** [comment]
#4896 does not fix this issue, I believe #4896 is actually performing the wrong check. Out of bounds access does not signify an unloaded record, rather it is just out of bounds access and should return undefined (no warning).

Rather the check here should be `internalModel !== undefined && internalModel.someFlagSayingIsHasBeenUnloadedAndIForgotTheName`

**Comment by stefanpenner** [comment]
After chatting with @hjdivad we feel this is actually no longer as issue. If a relationship has a member that is unloaded, the entire relationship has also been dematerialized and must be refetched anyways.
