### ISSUE TITLE
DS.Model.destroyRecord does not unload record from store

### ISSUE THREAD

**Issue by kweng2** [emberjs/data#5006]
#### Scenario:
```
const memberA = store.createRecord('member', { name: 'Bob' })
await memberA.save() // server responds with an id of 5678
await memberA.destroyRecord()
const memberB = store.createRecord('member', { name: 'Bob' })
await memberB.save() // server responds with an id of 5678
```

#### Expectation:
This should work no problem, memberA and memberB should be different records, that have the same 'name'

#### Reality:
```
You cannot update the id index of an InternalModel once set. Attempted to update ${id}.
```

I believe what's happening is that ```destroyRecord``` is not unloading the internalModel, and therefore upon creation throwing this error

On closer inspection, it does seem that ```store._removeFromIdMap``` and ```internalModel.destroy``` only get called from the ```unload``` method

It is unclear from the docs whether destroyRecord also removes internal references

**Comment by acorncom** [comment]
Related issue: https://github.com/emberjs/data/issues/4972

**Comment by pangratz** [comment]
I think this is fixed by #5126, so I am closing.

@kweng2 please reopen if you are still running into this issue after upgrading. Thanks!

**Comment by SergeAstapov** [comment]
This is still an issue in ember-data@2.16.3

I just hit exactly the same problem with exactly the same scenario as described in the first post.
I've tried to do
```
return coupon.destroyRecord().then(() => {
    this.get('store').unloadRecord(coupon);
});
```

But still got error `Error: Assertion Failed: 'coupon' was saved to the server, but the response returned the new id 'XXX', which has already been used with another record.'`

**Comment by maysam-tayyeb** [comment]
I checked the unloadRecod() and realised it does not unload destroyed record and therefore I unloaded my record using:

**Comment by erichonkanen** [comment]
related https://github.com/emberjs/data/issues/5237

**Comment by runspired** [comment]
This should be re-examined following the landing of #5378

**Comment by runspired** [comment]
#5455 is in-progress to address this; however, semantics and teardown timing issues around getting `deleteRecord` and `deleteRecord.save` correct on `isNew` records has held it up.
