### ISSUE TITLE
In upgrading from v2.13 to v2.15: broccoli-babel-transpiler is opting out of caching

### ISSUE THREAD

**Issue by raido** [emberjs/data#5164]
Upgrading ember-data from v2.13 to v2.15 (in addon) with "yarn upgrade ember-data" results in:
 
broccoli-babel-transpiler is opting out of caching due to a plugin that does not provide a caching strategy:

Probably some dependency needs to be bumped to avoid this.

Doing full "yarn upgrade" fixes the broccoli-babel-transpiler issue but introduces new warning:

"'instrument' is imported from external module 'ember-data/-debug' but never used"

**Comment by andrei-zhidkov** [comment]
I'm experiencing the same issue.
It seems like the problem is with `babel-plugin-transform-es2015-block-scoping`.

**Comment by xomaczar** [comment]
This has been fixed in #5114  /w tests...

**Comment by rwwagner90** [comment]
@xomaczar I still see the issue on ember-data 2.15.2. I get the opting out of caching message.

**Comment by xomaczar** [comment]
What's the error/warning?

**Comment by xomaczar** [comment]
Can you try 2.15.3

**Comment by rwwagner90** [comment]
@xomaczar same issue with 2.15.3. It's the same issue this issue says. `broccoli-babel-transpiler is opting out of caching due to a plugin that does not provide a caching strategy`

**Comment by rwjblue** [comment]
Can you share the full output of the warning? It generally includes the actual plugin code after that message (this will help us identify which plugin is causing the caching to be disabled)...

**Comment by rwwagner90** [comment]
@rwjblue sure thing!

```
broccoli-babel-transpiler is opting out of caching due to a plugin that does not provide a caching strategy: `function () {
  return {
    visitor: {
      VariableDeclaration: function VariableDeclaration(path, file) {
        var node = path.node,
            parent = path.parent,
            scope = path.scope;

        if (!isBlockScoped(node)) return;
        convertBlockScopedToVar(path, null, parent, scope, true);

        if (node._tdzThis) {
          var nodes = [node];

          for (var i = 0; i < node.declarations.length; i++) {
            var decl = node.declarations[i];
            if (decl.init) {
              var assign = t.assignmentExpression("=", decl.id, decl.init);
              assign._ignoreBlockScopingTDZ = true;
              nodes.push(t.expressionStatement(assign));
            }
            decl.init = file.addHelper("temporalUndefined");
          }

          node._blockHoist = 2;

          if (path.isCompletionRecord()) {
            nodes.push(t.expressionStatement(scope.buildUndefinedNode()));
          }

          path.replaceWithMultiple(nodes);
        }
      },
      Loop: function Loop(path, file) {
        var node = path.node,
            parent = path.parent,
            scope = path.scope;

        t.ensureBlock(node);
        var blockScoping = new BlockScoping(path, path.get("body"), parent, scope, file);
        var replace = blockScoping.run();
        if (replace) path.replaceWith(replace);
      },
      CatchClause: function CatchClause(path, file) {
        var parent = path.parent,
            scope = path.scope;

        var blockScoping = new BlockScoping(null, path.get("body"), parent, scope, file);
        blockScoping.run();
      },
      "BlockStatement|SwitchStatement|Program": function BlockStatementSwitchStatementProgram(path, file) {
 if (!ignoreBlock(path)) {
          var blockScoping = new BlockScoping(null, path, path.parent, path.scope, file);
          blockScoping.run();
        }
      }
    }
  };
}`.
```

**Comment by rwjblue** [comment]
Awesome, thank you!  I submitted #5196 to address.

**Comment by rwwagner90** [comment]
Thanks @rwjblue!

**Comment by musaffa** [comment]
@rwjblue Will this fix be released in ember-data 2.15 or 2.16?

**Comment by bmac** [comment]
@musaffa This fix should be in Ember Data 2.16.0.

**Comment by musaffa** [comment]
Thanks. I couldn't upgrade to 2.15 because of this issue. This is for the first time I couldn't upgrade.

**Comment by bmac** [comment]
Looks like @rwjblue's fix didn't get everything. There is a new pr https://github.com/emberjs/data/pull/5206 that will land in a 2.16.1 sometime tonight or tomorrow.

**Comment by scottkidder** [comment]
This is fixed for me on 2.16.2. Thanks everyone!
