### ISSUE TITLE
headersForRequest of RESTAdapter does not work

### ISSUE THREAD

**Issue by roman-gula** [emberjs/data#5171]
**headersForRequest** is called in **_requestFor** method wich can be called in some methods (for example **updateRecord**), but there is a condition

`if (isEnabled('ds-improved-ajax') && !this._hasCustomizedAjax())`

But feature _ds-improved-ajax_ was disabled. isEnabled('ds-improved-ajax') always returns undefined.

Why are public methods called in the private method?

**Comment by pangratz** [comment]
Hey @roman-gula, as you pointed out, the `ds-improved-ajax` feature is still disabled. But unfortunately those methods already show up in the API docs.

Do you want to help out and open a PR which removes the `@public` from the methods which are still behind a feature flag? So basically these:

https://github.com/emberjs/data/blob/5fceead8acb53723bdf38daabad00aff093f390a/addon/adapters/rest.js#L1248

https://github.com/emberjs/data/blob/5fceead8acb53723bdf38daabad00aff093f390a/addon/adapters/rest.js#L1306

https://github.com/emberjs/data/blob/5fceead8acb53723bdf38daabad00aff093f390a/addon/adapters/rest.js#L1326

https://github.com/emberjs/data/blob/5fceead8acb53723bdf38daabad00aff093f390a/addon/adapters/rest.js#L1366

**Comment by pangratz** [comment]
Fixed by #5212

**Comment by emoryy** [comment]
Guys, I see that the related pull request was already merged, but these methods under the ds-improved-ajax feature flag are still shown in the latest ember-data API documentation on the website, for example:

https://emberjs.com/api/ember-data/2.16/classes/DS.RESTAdapter/methods/dataForRequest?anchor=dataForRequest

Nothing has changed.
