### ISSUE TITLE
Inconsistent behaviour when using json api linked relationships

### ISSUE THREAD

**Issue by svenpl** [emberjs/data#5478]
I'm not sure if this is an actual bug but we have a few problems due to this behaviour in our application.

We are using EmberData 2.18.2 and the JSON API with linked relationships.
We have two models `contact` and `bank-account` which are related to each other via a one to many relation.

If we load a single bank account and its related contact and then try to call `contact.get('bankAccounts')` to get the rest of the bank accounts it won't trigger a request for the missing bank accounts.
But if we call `contact.hasMany('bankAccounts')` before loading the single bank account then the missing bank accounts will be loaded when calling `contact.get('bankAccounts')`.

Here is a [twiddle](https://ember-twiddle.com/1c4fa052c0d2e6c269cf9cf2145cb508?openFiles=routes.application.js%2C) which reproduces this.

**Comment by runspired** [comment]
This is fixed in 3.2

**Comment by iezer** [comment]
I have this issue as well as of 2.14. Any chance of back-porting this fix to some earlier versions?

**Comment by svenpl** [comment]
@runspired  I just updated my Twiddle for Ember 3.2.0 and unfortunately the behaviour is still the same.
[New twiddle](https://canary.ember-twiddle.com/1c4fa052c0d2e6c269cf9cf2145cb508?openFiles=twiddle.json%2C)
