### ISSUE TITLE
Cannot set relationship in 3.2.0

### ISSUE THREAD

**Issue by amk221** [emberjs/data#5517]
Clearing out the relationship then setting it no longer works.

e.g:

```javascript
myModel.setProperties({
  name: null,
  myRel: null
});

myModel.set('myRel', myRel);
```

Passing in 2.18.2: [Twiddle](https://ember-twiddle.com/11a0cd04ff9b89f0fa7ee399ccb94381?openFiles=tests.unit.foo-test.js%2C)
Switch to 3.2.0 for a failure

**Comment by amk221** [comment]
Oh, related to: https://github.com/emberjs/data/issues/5511

**Comment by acorncom** [comment]
This bug might be fixed now?

**Comment by runspired** [comment]
It is fixed.

**Comment by jrjohnson** [comment]
Oh OK, I still have a possibly related issue in 3.3.1. I will try and create a useful reproduction and a new ticket.

**Comment by amk221** [comment]
Same here, I tried emberjs/data#master, but still having problems

**Comment by runspired** [comment]
@amk221 I have mega doubts that this issue still exists on master without a reproducible failing scenario. I did look at the repro you mentioned here: https://github.com/amk221/-ember-data-geturl-not-a-function/commit/3ab9aa7d527cac88d126fdf81d7b87f0a13c02e4 and as others mentioned the test itself is incorrect and passes when fixed.

I noticed your comments:

> The actual test does some setting and unsetting of relationships. But still comes back with this error.
> i.e. Setting the relationship from null back to an ED model does not work due to the above bug in 5517, therefore, the test ends up deepEqualing an ED model with null, which triggers the error in question.

However we have tests that cover exactly this scenario, so without a clear test setup showing this problem still exists for some set of conditions I'm inclined to believe it's more likely an issue with app code.

**Comment by amk221** [comment]
I still get `(0 , _emberMetal.get)(...).getURL is not a function` with ED 3.5.0 in this minimal [test case](https://github.com/amk221/-ember-data-geturl-not-a-function/commit/0f9971183512174b56b81d0ea0a0aa5e5362de3a#diff-23f197cf50d875266a6a4204c22dcb92)

**Comment by dmarkin** [comment]
The bug is here.
I have the Model Offer, including
`type: belongsTo('offerType', {async: true})`
and Model Offer-type with some properties.
With updating from 2.12 to 3.5 Ember breaks down the app cause if I do
`offer.set('type', someNewTypeFromStore)`
I'll have finally
`offer.get('type') === null`

**Comment by Skwai** [comment]
We're seeing the same issue as @dmarkin  in `3.3.0`. Any work arounds?
