### ISSUE TITLE
Empty hasMany relationship not sent to server by model.save()

### ISSUE THREAD

**Issue by les2** [emberjs/data#5539]
While QAing our next release and we had to downgrade ember-data to 3.1.1 from 3.2.0 because of a weird bug.

When updating a `hasMany` relationship to an empty array and called `.save()` on the owning model, the empty array is not sent to the server.

example:

```
const Child = Model.extend({
   parent: belongsTo('parent', { async: false })
})

const Parent = Model.extend({
   items: hasMany('child', {async: false})
})
```

... later ...

```
const model = store.findRecord('parent', 99);
model.get('items').mapBy('id'); // ['1', '2', '3']

model.set('items', A());
model.save();
```

In 3.1.1, this worked --- an empty relationship would be sent to the server.

After upgrading to 3.2.0, it not longer sends the empty relationship.

Unfortunately, I haven't been able to put together a simple repo recipe on github - I only have the rather complicated example that is our application (which I can't share for obvious reasons).

I have to leave the office right now but will try to get some more details in this issue when I can (probably tomorrow).

That said, please be careful upgrading to 3.2.0 :)

**Comment by runspired** [comment]
@ryanto did your work land prior to 3.2 or is this related to it?

**Comment by les2** [comment]
@runspired @ryanto I suspect that [this line] is to blame. you can see it in the [diff from 3.1.1 to 3.2.0].

```
        // only serialize has many relationships that are not new
        let nonNewHasMany = hasMany.filter(item => item.record && !item.record.get('isNew'));

        if (nonNewHasMany.length > 0) { // <---- BUG HERE -- this line was added
          json.relationships = json.relationships || {};
             ...
            json.relationships[payloadKey] = { data }; // <---- when the hasMany relationship is empty, an item is never added here
          }
        }
 ```

To fix it, we could add logic for the case where the relationship is completely empty and then add an empty `data: []` item to the relationships hash.

### Aside
While looking at the code, I also observe that `isNew` items are not serialized. Seems like we should warn the user that the relationships aren't going to be persisted because they are `isNew`, or even throw a fatal error while in dev mode.

[this line]: https://github.com/emberjs/data/blob/7e02741865aaa951e876334ae36c490d4dd39573/addon/serializers/json-api.js#L522

[diff from 3.1.1 to 3.2.0]: https://github.com/emberjs/data/compare/v3.1.1...v3.2.0#diff-c939dc9dc1a354cd6a97bd2c4ab65333R522

**Comment by les2** [comment]
@ryanto @runspired Let me know if you'd like me to get a PR up - I'd love to contribute.

**Comment by ryanto** [comment]
@runspired What's the best way to know if a relationship is empty vs has-not-been-fetched? That sounds like the way to fix this?

**Comment by urbany** [comment]
@ryanto @runspired I looked at the commits and could only find that fix in v3.4.0-beta.1
Might be a good idea to release a v3.3.1 with that fix, alongside #5541

**Comment by urbany** [comment]
3.3.1 was just released but this is still not fixed, you have to use 3.4.0-beta.2

**Comment by runspired** [comment]
@urbany 3.3 was a re-release of 3.2. They are and will effectively remain the same release.

**Comment by ryanto** [comment]
Here are the PRs merging the fix back into...

3.2: https://github.com/emberjs/data/pull/5546

3.3: https://github.com/emberjs/data/pull/5547

**Comment by olivierchatry** [comment]
seems like 3.4 is also impacted. I have the same issue, and emberdata is clearly not serializing empty hasmany.

**Comment by ryanto** [comment]
Hi @olivierchatry,

Have you enabled serializing the hasMany relationship in your serializer?

```js
export default ApplicationSerializer.extend(, {
  attrs: {
    hasManyRelationshipNameHere: { serialize: true }
  }
});
```

**Comment by olivierchatry** [comment]
Haaa wait, my fault, I override a function in my app that was producing the bug. Sorry !

**Comment by ryanto** [comment]
Thanks @runspired !

Looks like the fix was released in `3.1.2` and `3.3.2`. If you're running into this, give those versions a try.

**Comment by fran-worley** [comment]
@ryanto 3.1.2 seems to work, but I still have the same issue in 3.3.2. @runspired can you confirm what the situation is with back-porting a fix to 3.3.x ?

**Comment by jfschaff** [comment]
Seems like I am having this issue in v3.4.4 (but not systematically on all models)...

**Comment by acdn-tsmith** [comment]
Also having the issue on 3.25

**Comment by runspired** [comment]
@acdn-tsmith its (more than) likely a different issue. A test PR or demo app/twiddle replicating the issue is welcome. If you can reproduce it please open a new issue for us!

Since serializers are predominantly an app-code (vs lib-code) concept, there's a relatively good chance you're seeing this due to code added or modified in your serializer. If you can't replicate without serializer modifications then that's something to look into.
