### ISSUE TITLE
ember-data@3.12 does not work in IE11

### ISSUE THREAD

**Issue by btecu** [emberjs/data#6380]
Steps to reproduce:
```
ember new test-ie
ember build --prod
```

When trying to browse in IE, the page will stay blank and throw:
```
SCRIPT5009: 'Symbol' is undefined
vendor.js (85124,5)
```

**Comment by raido** [comment]
I am targeting IE11 (including Browserstack running tests with IE11). The `const` is not a that much of a problem for me. The `Symbol` issue is, so perhaps let's keep this issue focused on that.

**Comment by raido** [comment]
https://github.com/emberjs/data/blob/63e13baf74ff97a3e08b6d7b1541a64695935316/packages/store/addon/-private/ts-interfaces/utils/brand.ts - basically this is the source of the issue I assume?

**Comment by raido** [comment]
It seems my testing with v3.11 was actually testing v3.12 anyway - https://github.com/emberjs/data/issues/6378 - because of floating versions.

**Comment by dcyriller** [comment]
I'll dig into it

**Comment by btecu** [comment]
@runspired can we please get a `3.12.1` release with this fix?

**Comment by runspired** [comment]
@btecu sure, but I believe there is one symbol still not being stripped.

**Comment by dcyriller** [comment]
The last Symbol to fix is present on master but not in v3.12. I still have to do the fix with WeakMap to solve the whole Symbol issue. I could port the current fix to 3.12 if you think it makes sense.

**Comment by runspired** [comment]
@dcyriller lets port the current fix so that we can fix 3.12 then get back to the WeakMap fix

**Comment by runspired** [comment]
3.12.1 with this fix has been released

**Comment by btecu** [comment]
Unfortunately, `ember-data` `3.12.1` still doesn't work with IE11.
I now get a different error:
![image](https://user-images.githubusercontent.com/7517745/64727610-38423200-d4a7-11e9-8d46-c66c3f3b457a.png)

I saw there's an issue #6326 about this, not specific to IE.
I do have `"jquery-integration": true`.
